### ISSUE TITLE
only modify LocatSettings.php if you have permission

### ISSUE THREAD

**Issue by HughR** [samwilson/MediaWiki_Backup#4]
Thanks for this script.

On my system, only root can write LocalSettings.php.  But anyone could do backups.

Your script doesn't quite work in this case.

Simple fix: wrap much of the body of toggle_read_only in this test:

if [ -w "$LOCALSETTINGS" ] ; then

   ...

fi

**Comment by samwilson** [comment]
Thanks for pointing this out! And I'm very sorry that it's taken me *two and a half years* to fix it. :-) But it's fixed now. That function returns early if the file isn't writable.
