### ISSUE TITLE
XML backup doesn't find LocalSettings.php

### ISSUE THREAD

**Issue by HughR** [samwilson/MediaWiki_Backup#5]
I get this error message

  A copy of your installation's LocalSettings.php
  must exist and be readable in the source directory.
  Use --conf to specify it.

It isn't clear from the wording but this is an error message and the XML backup isn't accomplished.

The fix is to add

  --conf="$INSTALL_DIR/LocalSettings.php"

to the php invocation that runs dumpBackup.php (line 137 in the current script).

The line becomes:

  php -d error_reporting=E_ERROR dumpBackup.php --conf="$INSTALL_DIR/LocalSettings.php" --quiet --full \

**Comment by samwilson** [comment]
Done!
