### ISSUE TITLE
dereference when tar'ing images directory?

### ISSUE THREAD

**Issue by samwilson** [samwilson/MediaWiki_Backup#7]
In case it's a symlink.

**Comment by yegorich** [comment]
@samwilson what about `tar --exclude-vcs -hzcf "$IMG_BACKUP" images`? Or at least make an option to enable such behavior?

**Comment by samwilson** [comment]
Yeah, I think you're right, a flag to add `--dereference` is required. Can't just change it to that, I think, it should default to the current behaviour. Maybe use the same letter? So `-h` would "follow symlinks for the images directory; archive and dump the files they point to".

**Comment by yegorich** [comment]
Yes, let's use '-h'.

**Comment by samwilson** [comment]
Done. Also added a warning if -h isn't specified but the images dir is a symlink.
