### ISSUE TITLE
Single archive issue

### ISSUE THREAD

**Issue by yegorich** [samwilson/MediaWiki_Backup#8]
As for now -s is not working as this passage renders it useless:

    ## Check whether a single archive file should be created
    SINGLE_ARCHIVE=false
    if [ -z $SINGLE_ARCHIVE ]; then
        SINGLE_ARCHIVE=true
    fi

You set SINGLE_ARCHIVE to false, so that if-statement has no meaning. In theory it would be good, if all three single *.gz files would be deleted after successful combining.

**Comment by samwilson** [comment]
Gosh, I do feel silly. :-)

I'll get this fixed posthaste.

Thanks for reporting.
